/* Generated by Together */

package nc.vo.hr.tools.dbtool.util.event;

import java.util.EventListener;
import java.util.EventObject;


/**
 * 默认事件分发器
 * @author 闫长海 
 */
public class BaseEventDispatcher implements IEventDispatcher {

    /* (non-Javadoc)
     * @see nc.ui.print.util.event.IEventDispatcher#dispatchEvent(java.util.EventObject, java.util.EventListener)
     */
    public void dispatchEvent(EventObject event, EventListener listener)throws Exception {
        if( listener instanceof BaseEventListener ) {
            ((BaseEventListener)listener).listenEvent( event );
        }else {
            throw new EventException("不是默认事件监听，事件不能进行分发");
        }
    }
}
