/* Generated by Together */

package nc.vo.hr.tools.dbtool.util.event;

/**
 * @author „∆≥§∫£ 
 */
public class EventServerConfig implements IEventServerConfig {
    
    private int eventExcuteType = EVENT_EXCUTE_SYNC;
    /* (non-Javadoc)
     * @see nc.ui.print.util.event.IEventServerConfig#getEventExcuteType()
     */
    public int getEventExcuteType() {
        return eventExcuteType;
    }

    /* (non-Javadoc)
     * @see nc.ui.print.util.event.IEventServerConfig#setEventExuteType(int)
     */
    public void setEventExuteType(int type) {
        this.eventExcuteType = type;
    }    
}
