/* Generated by Together */

package nc.vo.hr.tools.dbtool.util.event;

import java.util.EventListener;
import java.util.EventObject;

/**
 * 事件分发器，默认分发器按事件类和监听类匹配分发，若事件类有自定义分类，则定制事件分发器并注册即可。 
 * @author 闫长海
 */
public interface IEventDispatcher {
    
    void dispatchEvent( EventObject event , EventListener listener )throws Exception;
}
