/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.bankpub.orgbanktonc;

import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
import nc.vo.pub.lang.UFDate;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * 
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 
 * 创建日期:2008-12-9
 * 
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
public class OrgBankToNcVO extends SuperVO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6669680003833129545L;
	public String free3;
	public String bankname;
	public String free1;
	public UFDate ts;
	public String pk_deptdoc;
	public Integer dr;
	public String free5;
	public String bankcode;
	public String pk_corp;
	public String pk_orgbanktonc;
	public String free2;
	public String free4;

	public static final String FREE3 = "free3";
	public static final String BANKNAME = "bankname";
	public static final String FREE1 = "free1";
	public static final String TS = "ts";
	public static final String PK_DEPTDOC = "pk_deptdoc";
	public static final String DR = "dr";
	public static final String FREE5 = "free5";
	public static final String BANKCODE = "bankcode";
	public static final String PK_CORP = "pk_corp";
	public static final String PK_ORGBANKTONC = "pk_orgbanktonc";
	public static final String FREE2 = "free2";
	public static final String FREE4 = "free4";

	/**
	 * 属性free3的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getFree3() {
		return free3;
	}

	/**
	 * 属性free3的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newFree3
	 *            String
	 */
	public void setFree3(String newFree3) {

		free3 = newFree3;
	}

	/**
	 * 属性bankname的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getBankname() {
		return bankname;
	}

	/**
	 * 属性bankname的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newBankname
	 *            String
	 */
	public void setBankname(String newBankname) {

		bankname = newBankname;
	}

	/**
	 * 属性free1的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getFree1() {
		return free1;
	}

	/**
	 * 属性free1的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newFree1
	 *            String
	 */
	public void setFree1(String newFree1) {

		free1 = newFree1;
	}

	/**
	 * 属性ts的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public UFDate getTs() {
		return ts;
	}

	/**
	 * 属性ts的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newTs
	 *            String
	 */
	public void setTs(UFDate newTs) {

		ts = newTs;
	}

	/**
	 * 属性pk_deptdoc的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getPk_deptdoc() {
		return pk_deptdoc;
	}

	/**
	 * 属性pk_deptdoc的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newPk_deptdoc
	 *            String
	 */
	public void setPk_deptdoc(String newPk_deptdoc) {

		pk_deptdoc = newPk_deptdoc;
	}

	/**
	 * 属性dr的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return Integer
	 */
	public Integer getDr() {
		return dr;
	}

	/**
	 * 属性dr的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newDr
	 *            Integer
	 */
	public void setDr(Integer newDr) {

		dr = newDr;
	}

	/**
	 * 属性free5的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getFree5() {
		return free5;
	}

	/**
	 * 属性free5的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newFree5
	 *            String
	 */
	public void setFree5(String newFree5) {

		free5 = newFree5;
	}

	/**
	 * 属性bankcode的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getBankcode() {
		return bankcode;
	}

	/**
	 * 属性bankcode的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newBankcode
	 *            String
	 */
	public void setBankcode(String newBankcode) {

		bankcode = newBankcode;
	}

	/**
	 * 属性pk_corp的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getPk_corp() {
		return pk_corp;
	}

	/**
	 * 属性pk_corp的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newPk_corp
	 *            String
	 */
	public void setPk_corp(String newPk_corp) {

		pk_corp = newPk_corp;
	}

	/**
	 * 属性pk_orgbanktonc的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getPk_orgbanktonc() {
		return pk_orgbanktonc;
	}

	/**
	 * 属性pk_orgbanktonc的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newPk_orgbanktonc
	 *            String
	 */
	public void setPk_orgbanktonc(String newPk_orgbanktonc) {

		pk_orgbanktonc = newPk_orgbanktonc;
	}

	/**
	 * 属性free2的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getFree2() {
		return free2;
	}

	/**
	 * 属性free2的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newFree2
	 *            String
	 */
	public void setFree2(String newFree2) {

		free2 = newFree2;
	}

	/**
	 * 属性free4的Getter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getFree4() {
		return free4;
	}

	/**
	 * 属性free4的Setter方法.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newFree4
	 *            String
	 */
	public void setFree4(String newFree4) {

		free4 = newFree4;
	}

	/**
	 * 验证对象各属性之间的数据逻辑正确性.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @exception nc.vo.pub.ValidationException
	 *                如果验证失败,抛出 ValidationException,对错误进行解释.
	 */
	public void validate() throws ValidationException {

		ArrayList errFields = new ArrayList(); // errFields record those null

		// fields that cannot be null.
		// 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:

		StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
			String[] temp = (String[]) errFields.toArray(new String[0]);
			message.append(temp[0]);
			for (int i = 1; i < temp.length; i++) {
				message.append(",");
				message.append(temp[i]);
			}
			throw new NullFieldException(message.toString());
		}
	}

	/**
	 * <p>
	 * 取得父VO主键字段.
	 * <p>
	 * 创建日期:2008-12-9
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getParentPKFieldName() {

		return null;

	}

	/**
	 * <p>
	 * 取得表主键.
	 * <p>
	 * 创建日期:2008-12-9
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getPKFieldName() {
		return "pk_orgbanktonc";
	}

	/**
	 * <p>
	 * 返回表名称.
	 * <p>
	 * 创建日期:2008-12-9
	 * 
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {

		return "bank_orgbanktonc";
	}

	/**
	 * 按照默认方式创建构造子.
	 * 
	 * 创建日期:2008-12-9
	 */
	public OrgBankToNcVO() {

		super();
	}

	/**
	 * 使用主键进行初始化的构造子.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newPk_orgbanktonc
	 *            主键值
	 */
	public OrgBankToNcVO(String newPk_orgbanktonc) {

		// 为主键字段赋值:
		pk_orgbanktonc = newPk_orgbanktonc;

	}

	/**
	 * 返回对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return String
	 */
	public String getPrimaryKey() {

		return pk_orgbanktonc;

	}

	/**
	 * 设置对象标识,用来唯一定位对象.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @param newPk_orgbanktonc
	 *            String
	 */
	public void setPrimaryKey(String newPk_orgbanktonc) {

		pk_orgbanktonc = newPk_orgbanktonc;

	}

	/**
	 * 返回数值对象的显示名称.
	 * 
	 * 创建日期:2008-12-9
	 * 
	 * @return java.lang.String 返回数值对象的显示名称.
	 */
	public String getEntityName() {

		return "bank_orgbanktonc";

	}
}
