  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.bankpub.tallyrole;
   	
	import java.util.ArrayList;

import nc.vo.pub.NullFieldException;
import nc.vo.pub.SuperVO;
import nc.vo.pub.ValidationException;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2008-9-21
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class TallyRoleVO extends SuperVO {
           
             public String pk_corp;
             public String pk_role;
             public String pk_tallyroles;
             public String ts;
             public Integer dr;
            
             public static final String  PK_CORP="pk_corp";   
             public static final String  PK_ROLE="pk_role";   
             public static final String  PK_TALLYROLES="pk_tallyroles";   
             public static final String  TS="ts";   
             public static final String  DR="dr";   
      
    
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2008-9-21
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2008-9-21
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性pk_role的Getter方法.
	   *
	   * 创建日期:2008-9-21
	   * @return String
	   */
	 public String getPk_role() {
		 return pk_role;
	  }   
	  
     /**
	   * 属性pk_role的Setter方法.
	   *
	   * 创建日期:2008-9-21
	   * @param newPk_role String
	   */
	public void setPk_role(String newPk_role) {
		
		pk_role = newPk_role;
	 } 	  
       
        /**
	   * 属性pk_tallyroles的Getter方法.
	   *
	   * 创建日期:2008-9-21
	   * @return String
	   */
	 public String getPk_tallyroles() {
		 return pk_tallyroles;
	  }   
	  
     /**
	   * 属性pk_tallyroles的Setter方法.
	   *
	   * 创建日期:2008-9-21
	   * @param newPk_tallyroles String
	   */
	public void setPk_tallyroles(String newPk_tallyroles) {
		
		pk_tallyroles = newPk_tallyroles;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2008-9-21
	   * @return String
	   */
	 public String getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2008-9-21
	   * @param newTs String
	   */
	public void setTs(String newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2008-9-21
	   * @return UFDouble
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2008-9-21
	   * @param newDr UFDouble
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2008-9-21
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2008-9-21
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2008-9-21
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_tallyroles";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2008-9-21
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "bank_tallyroles";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2008-9-21
	  */
	public TallyRoleVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2008-9-21
	 * @param newPk_tallyroles 主键值
	 */
	 public TallyRoleVO(String newPk_tallyroles) {
		
		// 为主键字段赋值:
		 pk_tallyroles = newPk_tallyroles;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2008-9-21
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_tallyroles;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2008-9-21
	  * @param newPk_tallyroles  String    
	  */
	 public void setPrimaryKey(String newPk_tallyroles) {
				
				pk_tallyroles = newPk_tallyroles; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2008-9-21
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "bank_tallyroles"; 
				
	 } 
} 
